#!/usr/bin/env bash

# Youtube download transcript

set -e

# Check url
if [[ $1 ]]; then
  yt_url="$1"
  yt_trans_file=transcricao.pt.srt
else
  echo 'error: need url' >&2
  exit 1
fi

# Check yt-dlp
if ! type yt-dlp  >/dev/null; then
  echo 'error: need yt-dlp' >&2
  exit 1
fi

# Get transcript
if [[ ! -f "$yt_trans_file" ]]; then
  yt-dlp \
    --skip-download \
    --sub-format srt \
    --sub-lang pt \
    --write-subs \
    --write-auto-subs \
    --quiet \
    --output "transcricao" \
    "$yt_url"  
fi

# Get format transcript from
yt_trans_txt=$(awk -f format.awk "$yt_trans_file")

read -rp '
Escolha uma opção:
p) Print
g) Gui
s) Save
q) Quit

Opção: ' opc

case "$opc" in
  p) echo "$yt_trans_txt" ;;
  g) 
    if type yad  >/dev/null; then
      ./gui "$yt_trans_file"
    else
      echo 'error: need yad to gui' >&2
      exit 1
    fi
    ;;
  s) echo "$yt_trans_txt" > transcricao.txt ;;
  q) exit 0 ;;
esac
